// <auto-generated />
using System;
using AK.BlogWebApp.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AK.BlogWebApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510010131_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.AboutPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AboutPages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            CreatedDate = new DateTime(2025, 5, 10, 1, 1, 31, 111, DateTimeKind.Utc).AddTicks(6981),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImgUrl = "full-stack-devlopment-min_20250510_033652.png",
                            IsActive = true,
                            Title = "What is Lorem Ipsum?"
                        });
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HomePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.HasIndex("HomePageId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f802b23-dd96-41a9-88bc-8e923cba6be9"),
                            BlogCategoryId = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            CoverImgUrl = "angular_20250510_033323.png",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsFeatured = false,
                            Title = "What is Lorem Ipsum?\r\n"
                        },
                        new
                        {
                            Id = new Guid("692158c3-96b4-4749-8fa3-1c9568281445"),
                            BlogCategoryId = new Guid("0b6c5c91-9d48-4e9b-8b5d-fed05be56a73"),
                            Content = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n\r\n",
                            CoverImgUrl = "dotnet_20250510_033308.png",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsFeatured = false,
                            Title = "Where does it come from?\r\n"
                        },
                        new
                        {
                            Id = new Guid("270445c6-56f7-46eb-b27f-a01e2885c0e7"),
                            BlogCategoryId = new Guid("6def4f3d-93b9-4c24-97e1-143499f2955f"),
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            CoverImgUrl = "full-stack-devlopment-min_20250510_033344.png",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsFeatured = true,
                            Title = "What is Lorem Ipsum?\r\n"
                        },
                        new
                        {
                            Id = new Guid("05283987-d4c9-48b3-9e42-06bc362805f3"),
                            BlogCategoryId = new Guid("d7a19c6c-0d9f-4d10-9207-cfc9c8499a32"),
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            CoverImgUrl = "images_20250510_033400.jpeg",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsFeatured = true,
                            Title = "What is Lorem Ipsum?\r\n"
                        },
                        new
                        {
                            Id = new Guid("b7b9e1cc-1625-474f-a40e-e4cc1371d719"),
                            BlogCategoryId = new Guid("d7a19c6c-0d9f-4d10-9207-cfc9c8499a32"),
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            CoverImgUrl = "rest-api_20250510_033416.jpg",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsFeatured = true,
                            Title = "What is Lorem Ipsum?\r\n"
                        });
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 111, DateTimeKind.Local).AddTicks(9403),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        },
                        new
                        {
                            Id = new Guid("0b6c5c91-9d48-4e9b-8b5d-fed05be56a73"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 111, DateTimeKind.Local).AddTicks(9421),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        },
                        new
                        {
                            Id = new Guid("6def4f3d-93b9-4c24-97e1-143499f2955f"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 111, DateTimeKind.Local).AddTicks(9423),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        },
                        new
                        {
                            Id = new Guid("d7a19c6c-0d9f-4d10-9207-cfc9c8499a32"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 111, DateTimeKind.Local).AddTicks(9425),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        });
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.ContactPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactPages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "ataberk@ataberkkaya.com",
                            IsActive = false,
                            PhoneNumber = "+90 999 999 99 99",
                            Title = "What is Lorem Ipsum?"
                        });
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HomePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCategoryId");

                    b.HasIndex("HomePageId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f802b23-dd96-41a9-88bc-8e923cba6be9"),
                            CoverImgUrl = "angular_20250510_033510.png",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            DocumentCategoryId = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            DocumentUrl = "angular_20250510_033510.png",
                            IsActive = false,
                            IsFeatured = false,
                            Title = "What is Lorem Ipsum?\r\n"
                        },
                        new
                        {
                            Id = new Guid("692158c3-96b4-4749-8fa3-1c9568281445"),
                            CoverImgUrl = "dotnet_2_20250510_033455.png",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n\r\n",
                            DocumentCategoryId = new Guid("0b6c5c91-9d48-4e9b-8b5d-fed05be56a73"),
                            DocumentUrl = "angular_20250510_033528.png",
                            IsActive = false,
                            IsFeatured = false,
                            Title = "Where does it come from?\r\n"
                        },
                        new
                        {
                            Id = new Guid("270445c6-56f7-46eb-b27f-a01e2885c0e7"),
                            CoverImgUrl = "dotnet_2_20250510_033541.png",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            DocumentCategoryId = new Guid("6def4f3d-93b9-4c24-97e1-143499f2955f"),
                            DocumentUrl = "dotnet_2_20250510_033455.png",
                            IsActive = false,
                            IsFeatured = true,
                            Title = "What is Lorem Ipsum?\r\n"
                        },
                        new
                        {
                            Id = new Guid("05283987-d4c9-48b3-9e42-06bc362805f3"),
                            CoverImgUrl = "full-stack-devlopment-min_20250510_033528.png",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            DocumentCategoryId = new Guid("d7a19c6c-0d9f-4d10-9207-cfc9c8499a32"),
                            DocumentUrl = "dotnet_2_20250510_033541.png",
                            IsActive = false,
                            IsFeatured = true,
                            Title = "What is Lorem Ipsum?\r\n"
                        },
                        new
                        {
                            Id = new Guid("b7b9e1cc-1625-474f-a40e-e4cc1371d719"),
                            CoverImgUrl = "rest-api_20250510_033440.jpg",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\r\n\r\n",
                            DocumentCategoryId = new Guid("d7a19c6c-0d9f-4d10-9207-cfc9c8499a32"),
                            DocumentUrl = "dotnet_2_20250510_033559.png",
                            IsActive = false,
                            IsFeatured = true,
                            Title = "What is Lorem Ipsum?\r\n"
                        });
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.DocumentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DocumentCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 112, DateTimeKind.Local).AddTicks(954),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        },
                        new
                        {
                            Id = new Guid("0b6c5c91-9d48-4e9b-8b5d-fed05be56a73"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 112, DateTimeKind.Local).AddTicks(957),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        },
                        new
                        {
                            Id = new Guid("6def4f3d-93b9-4c24-97e1-143499f2955f"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 112, DateTimeKind.Local).AddTicks(962),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        },
                        new
                        {
                            Id = new Guid("d7a19c6c-0d9f-4d10-9207-cfc9c8499a32"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 112, DateTimeKind.Local).AddTicks(963),
                            IsActive = false,
                            Title = "What is Lorem Ipsum?"
                        });
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.HeaderArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HeaderAreas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ataberk",
                            IsActive = false,
                            LastName = "Kaya",
                            Profession = "Full Stack Software Developer"
                        });
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.HomePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeaderContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MainContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HomePages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58eb3902-48a5-48e7-b5a8-b43847f0f6bf"),
                            CreatedDate = new DateTime(2025, 5, 10, 4, 1, 31, 112, DateTimeKind.Local).AddTicks(2199),
                            HeaderContent = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            HeaderTitle = "What is Lorem Ipsum?",
                            IsActive = true,
                            MainContent = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            MainTitle = "What is Lorem Ipsum?"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.Blog", b =>
                {
                    b.HasOne("AK.BlogWebApp.Domain.Entities.BlogCategory", "BlogCategory")
                        .WithMany()
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AK.BlogWebApp.Domain.Entities.HomePage", null)
                        .WithMany("FeaturedBlogs")
                        .HasForeignKey("HomePageId");

                    b.Navigation("BlogCategory");
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.Document", b =>
                {
                    b.HasOne("AK.BlogWebApp.Domain.Entities.DocumentCategory", "DocumentCategory")
                        .WithMany()
                        .HasForeignKey("DocumentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AK.BlogWebApp.Domain.Entities.HomePage", null)
                        .WithMany("FeaturedDocuments")
                        .HasForeignKey("HomePageId");

                    b.Navigation("DocumentCategory");
                });

            modelBuilder.Entity("AK.BlogWebApp.Domain.Entities.HomePage", b =>
                {
                    b.Navigation("FeaturedBlogs");

                    b.Navigation("FeaturedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
